name: My Spider Workflow
on:
  push:
    branches:
      - main
on:
  schedule:
    - cron: '0 2 * * *'
on:
  workflow_dispatch:
jobs:
  run-spider:
    runs-on: ubuntu - latest
steps:
  - name: Checkout code
    uses: actions/checkout@v2
  - name: Set up Python
    uses: actions/setup-python@v2
    with:
      python-version: 3.9
  - name: Run spider script
    run: python spider.py
